name: color_thief_flutter
description: Grab the color palette from an image, the Flutter implementation of color-thief.
version: 1.0.2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # quantize_dart:
  #   git:
  #     url: https://github.com/JaonFanwt/quantize_dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
